# Generated by Django 4.2.16 on 2026-07-15 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username Telegram')),
                ('display_name', models.CharField(max_length=100, verbose_name='Имя в рейтинге')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Класс')),
                ('goal', models.CharField(choices=[('ct', 'Подготовка к ЦТ'), ('ce', 'Подготовка к ЦЭ'), ('attestat', 'Аттестат после 9 класса'), ('improve', 'Подтянуть предмет')], max_length=20, verbose_name='Цель обучения')),
                ('exam_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год сдачи экзамена')),
                ('timezone_name', models.CharField(default='Europe/Minsk', max_length=64, verbose_name='Часовой пояс')),
                ('is_pro', models.BooleanField(default=False, verbose_name='Pro-подписка')),
                ('pro_until', models.DateTimeField(blank=True, null=True, verbose_name='Pro до')),
                ('xp', models.PositiveIntegerField(default=0, verbose_name='Опыт (XP)')),
                ('streak_days', models.PositiveSmallIntegerField(default=0, verbose_name='Серия дней')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Последняя активность')),
                ('daily_tasks_completed', models.PositiveSmallIntegerField(default=0, verbose_name='Заданий выполнено сегодня')),
                ('registration_completed', models.BooleanField(default=False, verbose_name='Регистрация завершена')),
                ('tg_blocked', models.BooleanField(default=False, verbose_name='Бот заблокирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.city', verbose_name='Город')),
                ('exam_track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='knowledge.examtrack', verbose_name='Экзаменационный трек')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.school', verbose_name='Школа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='knowledge.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'indexes': [models.Index(fields=['-xp', 'created_at'], name='students_st_xp_b8772f_idx'), models.Index(fields=['city', '-xp'], name='students_st_city_id_501e6c_idx'), models.Index(fields=['school', '-xp'], name='students_st_school__98fdfb_idx')],
            },
        ),
    ]
