# Generated by Django 4.2.16 on 2026-07-16 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='ParentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_invites', to='students.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Код для родителя',
                'verbose_name_plural': 'Коды для родителей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentChildLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Привязан')),
                ('notify_weekly', models.BooleanField(default=True, verbose_name='Недельный отчёт')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='students.parent', verbose_name='Родитель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='students.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Связь родитель–ребёнок',
                'verbose_name_plural': 'Связи родитель–ребёнок',
                'ordering': ['-linked_at'],
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
