# Generated by Django 4.2.16 on 2026-08-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_parent_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Ежедневные уведомления'),
        ),
    ]
