# Generated by Django 4.2.16 on 2026-08-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_notifications_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='ID заказа')),
                ('plan_code', models.CharField(default='pro_1m', max_length=30, verbose_name='Код тарифа')),
                ('amount_byn', models.DecimalField(decimal_places=2, default=19.9, max_digits=8, verbose_name='Сумма (BYN)')),
                ('days', models.PositiveIntegerField(default=30, verbose_name='Дней подписки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('bepaid_checkout_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на оплату bePaid')),
                ('bepaid_token', models.CharField(blank=True, max_length=255, verbose_name='Токен bePaid')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='students.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Счёт bePaid / ЕРИП',
                'verbose_name_plural': 'Счета bePaid / ЕРИП',
                'ordering': ['-created_at'],
            },
        ),
    ]
