# Generated by Django 4.2.16 on 2026-08-21 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_paymentorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Время в Mini App (сек)')),
                ('session_count', models.PositiveIntegerField(default=1, verbose_name='Сессий за день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='students.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Сессия и время активности',
                'verbose_name_plural': 'Сессии и время активности',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
