# Generated by Django 4.2.16 on 2026-08-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_usersessionlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', '-paid_at'], name='students_pa_status_f1f685_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['student', '-created_at'], name='students_pa_student_2074e0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['registration_completed', 'grade'], name='students_st_registr_228bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['-last_activity_date'], name='students_st_last_ac_fcf78e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['-created_at'], name='students_st_created_b34044_idx'),
        ),
    ]
