# Generated by Django 4.2.16 on 2026-07-15 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('title', models.CharField(max_length=255, verbose_name='Название версии')),
                ('source_url', models.URLField(blank=True, verbose_name='Ссылка на источник')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущая версия')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Версия контента',
                'verbose_name_plural': 'Версии контента',
                'ordering': ['-year', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='ExamTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название трека')),
                ('track_type', models.CharField(choices=[('ct_11', 'ЦТ после 11 класса'), ('ce_11', 'ЦЭ после 11 класса'), ('attestat_9', 'Аттестат после 9 класса'), ('general', 'Общая подготовка')], max_length=20, verbose_name='Тип экзамена')),
                ('grade_from', models.PositiveSmallIntegerField(default=1, verbose_name='Класс от')),
                ('grade_to', models.PositiveSmallIntegerField(default=11, verbose_name='Класс до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Экзаменационный трек',
                'verbose_name_plural': 'Экзаменационные треки',
                'ordering': ['subject', 'grade_from'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='knowledge.contentversion', verbose_name='Версия контента')),
                ('exam_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='knowledge.examtrack', verbose_name='Экзаменационный трек')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Условие задания')),
                ('answer_format', models.CharField(choices=[('single_choice', 'Один вариант ответа'), ('multiple_choice', 'Несколько вариантов'), ('text', 'Текстовый ответ'), ('number', 'Числовой ответ')], default='single_choice', max_length=20, verbose_name='Формат ответа')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкое'), ('medium', 'Среднее'), ('hard', 'Сложное')], default='medium', max_length=10, verbose_name='Сложность')),
                ('source', models.CharField(blank=True, help_text='Сборник РИКЗ, учебник и т.д.', max_length=255, verbose_name='Источник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('authors', models.CharField(blank=True, max_length=255, verbose_name='Авторы')),
                ('publisher', models.CharField(blank=True, max_length=150, verbose_name='Издательство')),
                ('grade_level', models.PositiveSmallIntegerField(verbose_name='Класс')),
                ('file', models.FileField(blank=True, null=True, upload_to='textbooks/', verbose_name='Файл учебника (PDF)')),
                ('external_url', models.URLField(blank=True, verbose_name='Ссылка на учебник')),
                ('is_official', models.BooleanField(default=True, verbose_name='Официальный источник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('content_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textbooks', to='knowledge.contentversion', verbose_name='Версия контента')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='knowledge.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Учебник',
                'verbose_name_plural': 'Учебники',
                'ordering': ['subject', 'grade_level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TextbookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название главы')),
                ('chapter_number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер главы')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='knowledge.textbook', verbose_name='Учебник')),
            ],
            options={
                'verbose_name': 'Глава учебника',
                'verbose_name_plural': 'Главы учебников',
                'ordering': ['order', 'chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название темы')),
                ('grade_level', models.PositiveSmallIntegerField(blank=True, help_text='К какому классу относится тема.', null=True, verbose_name='Класс')),
                ('exam_weight', models.FloatField(default=1.0, help_text='Чем выше — тем чаще попадает в подборку.', verbose_name='Вес на экзамене')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='knowledge.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TopicSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Конспект')),
                ('key_points', models.TextField(blank=True, verbose_name='Ключевые правила')),
                ('source_note', models.CharField(blank=True, help_text='Учебник, программа, спецификация РИКЗ.', max_length=255, verbose_name='Источник')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='knowledge.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Конспект темы',
                'verbose_name_plural': 'Конспекты тем',
            },
        ),
        migrations.CreateModel(
            name='TextbookFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок фрагмента')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('page_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Страница от')),
                ('page_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Страница до')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='knowledge.textbookchapter', verbose_name='Глава')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textbook_fragments', to='knowledge.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Фрагмент учебника',
                'verbose_name_plural': 'Фрагменты учебников',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код типа')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание формата')),
                ('max_score', models.PositiveSmallIntegerField(default=1, verbose_name='Макс. балл')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('exam_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='knowledge.examtrack', verbose_name='Экзаменационный трек')),
            ],
            options={
                'verbose_name': 'Тип задания',
                'verbose_name_plural': 'Типы заданий',
                'ordering': ['order'],
                'unique_together': {('exam_track', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaskSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('explanation', models.TextField(verbose_name='Разбор решения')),
                ('common_mistakes', models.TextField(blank=True, verbose_name='Типичные ошибки')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='knowledge.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Решение задания',
                'verbose_name_plural': 'Решения заданий',
            },
        ),
        migrations.CreateModel(
            name='TaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='knowledge.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='knowledge.tasktype', verbose_name='Тип задания'),
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='knowledge.topic', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='examtrack',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_tracks', to='knowledge.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to='knowledge.subject', verbose_name='Предмет'),
        ),
    ]
