# Generated by Django 4.2.16 on 2026-07-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('publisher', models.CharField(blank=True, max_length=150, verbose_name='Издательство')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('isbn', models.CharField(blank=True, max_length=32, verbose_name='ISBN')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='Файл в info/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_collections', to='knowledge.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Сборник вариантов',
                'verbose_name_plural': 'Сборники вариантов',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExamVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер варианта')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Подпись')),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Год ЦТ/ЦЭ, если известен', null=True, verbose_name='Год экзамена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='knowledge.examcollection', verbose_name='Сборник')),
            ],
            options={
                'verbose_name': 'Вариант экзамена',
                'verbose_name_plural': 'Варианты экзамена',
                'ordering': ['collection', 'number'],
                'unique_together': {('collection', 'number')},
            },
        ),
        migrations.CreateModel(
            name='VariantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Номер в варианте')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_links', to='knowledge.task', verbose_name='Задание')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_tasks', to='knowledge.examvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Задание варианта',
                'verbose_name_plural': 'Задания вариантов',
                'ordering': ['order'],
                'unique_together': {('variant', 'task'), ('variant', 'order')},
            },
        ),
    ]
