# Generated by Django 4.2.16 on 2026-07-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_examcollection_examvariant_varianttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год шкалы')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('max_primary', models.PositiveSmallIntegerField(default=80, verbose_name='Макс. первичный балл')),
                ('source_url', models.URLField(blank=True, verbose_name='Источник')),
                ('is_current', models.BooleanField(default=True, verbose_name='Текущая')),
                ('exam_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_scales', to='knowledge.examtrack', verbose_name='Экзаменационный трек')),
            ],
            options={
                'verbose_name': 'Шкала баллов',
                'verbose_name_plural': 'Шкалы баллов',
                'ordering': ['-year', 'exam_track'],
                'unique_together': {('exam_track', 'year')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='scoring_scheme',
            field=models.CharField(choices=[('bin1', '0 или 1'), ('bin2', '0 или 2'), ('part2', '0 / 1 / 2 (частично верно)')], default='part2', help_text='Как на ЦТ/ЦЭ: часть A обычно 0/1/2, часть B — 0/2 или 0/1/2', max_length=10, verbose_name='Схема первичных баллов'),
        ),
        migrations.CreateModel(
            name='ScoreScaleRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_score', models.PositiveSmallIntegerField(verbose_name='Первичный балл')),
                ('test_score', models.PositiveSmallIntegerField(verbose_name='Тестовый балл')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='knowledge.scorescale', verbose_name='Шкала')),
            ],
            options={
                'verbose_name': 'Строка шкалы',
                'verbose_name_plural': 'Строки шкалы',
                'ordering': ['primary_score'],
                'unique_together': {('scale', 'primary_score')},
            },
        ),
    ]
