# Generated by Django 4.2.16 on 2026-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_scoring_and_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='Для 1–4 класса: иллюстрация в условии', null=True, upload_to='tasks/%Y/%m/', verbose_name='Картинка к заданию'),
        ),
        migrations.AddField(
            model_name='taskoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_options/%Y/%m/', verbose_name='Картинка варианта'),
        ),
        migrations.AlterField(
            model_name='examcollection',
            name='source_file',
            field=models.CharField(blank=True, max_length=255, verbose_name='Файл в materials/'),
        ),
    ]
