# Generated by Django 4.2.16 on 2026-08-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_task_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reading_text',
            field=models.TextField(blank=True, default='', help_text='Полный текст или отрывок из РИКЗ, к которому относится вопрос (например, предл. 1–25)', verbose_name='Текст к заданию / Прочитанный текст'),
        ),
    ]
