# Generated by Django 4.2.16 on 2026-08-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_task_reading_text'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['topic', 'is_active', 'id'], name='knowledge_t_topic_i_aa1b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['answer_format', 'is_active', 'id'], name='knowledge_t_answer__28b51f_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['grade_level', 'is_active'], name='knowledge_t_grade_l_fb3c29_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['section', 'is_active'], name='knowledge_t_section_018b32_idx'),
        ),
    ]
