# Generated by Django 4.2.16 on 2026-09-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_task_knowledge_t_topic_i_aa1b1e_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_active', 'source'], name='knowledge_t_is_acti_5e0ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='taskoption',
            index=models.Index(fields=['task', 'order'], name='knowledge_t_task_id_f46abd_idx'),
        ),
        migrations.AddIndex(
            model_name='taskoption',
            index=models.Index(fields=['task', 'is_correct'], name='knowledge_t_task_id_bb631c_idx'),
        ),
    ]
