# Generated by Django 4.2.16 on 2026-09-22 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_task_knowledge_t_is_acti_5e0ab3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicExtraTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос / Условие')),
                ('reading_text', models.TextField(blank=True, default='', verbose_name='Текст к вопросу')),
                ('options', models.JSONField(blank=True, default=list, help_text='Список вариантов ответов', verbose_name='Варианты ответа')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение / Правило')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкое'), ('medium', 'Среднее'), ('hard', 'Сложное')], default='medium', max_length=20, verbose_name='Сложность')),
                ('source', models.CharField(default='ai_generated', max_length=100, verbose_name='Источник генерации')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_tasks', to='knowledge.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Дополнительное задание',
                'verbose_name_plural': 'Дополнительные задания',
                'ordering': ['topic', 'order', 'id'],
                'indexes': [models.Index(fields=['topic', 'is_active'], name='knowledge_t_topic_i_4ec4cd_idx')],
            },
        ),
    ]
