# Generated by Django 4.2.16 on 2026-09-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_topicextratask'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicextratask',
            name='image',
            field=models.ImageField(blank=True, help_text='Красочная карточка или иллюстрация к заданию', null=True, upload_to='extra_tasks/%Y/%m/', verbose_name='Картинка к заданию'),
        ),
        migrations.AddField(
            model_name='topicextratask',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL или путь к картинке'),
        ),
    ]
