# Generated by Django 4.2.16 on 2026-07-15 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_mode_enabled', models.BooleanField(default=True, help_text='Если выключено — доступ только у Pro-пользователей.', verbose_name='Бесплатный режим включён')),
                ('free_daily_tasks_limit', models.PositiveSmallIntegerField(default=3, verbose_name='Лимит заданий в день (бесплатно)')),
                ('free_ai_explanations_enabled', models.BooleanField(default=False, verbose_name='ИИ-разбор ошибок в бесплатном режиме')),
                ('pro_ai_explanations_enabled', models.BooleanField(default=True, verbose_name='ИИ-разбор ошибок в Pro-режиме')),
                ('daily_session_tasks_count', models.PositiveSmallIntegerField(default=5, verbose_name='Заданий в ежедневной сессии')),
                ('weak_topic_task_ratio', models.FloatField(default=0.6, verbose_name='Доля заданий по слабым темам (0–1)')),
                ('xp_per_correct_answer', models.PositiveSmallIntegerField(default=10, verbose_name='XP за правильный ответ')),
                ('streak_bonus_xp', models.PositiveSmallIntegerField(default=5, verbose_name='Бонус XP за серию дней')),
                ('welcome_message', models.TextField(blank=True, verbose_name='Приветственное сообщение бота')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки приложения',
                'verbose_name_plural': 'Настройки приложения',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название города')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Область')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название школы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='core.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'ordering': ['city__name', 'name'],
                'unique_together': {('city', 'name')},
            },
        ),
    ]
