# Generated by Django 4.2.16 on 2026-07-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='free_ai_explanations_enabled',
            field=models.BooleanField(default=True, help_text='Показывает эталон+конспект. Живой LLM-разбор — только Pro.', verbose_name='Базовый разбор в free (без LLM)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='free_daily_tasks_limit',
            field=models.PositiveSmallIntegerField(default=15, help_text='Pro — без лимита. Для теста продукта можно поднять.', verbose_name='Лимит заданий в день (бесплатно)'),
        ),
    ]
