# Generated by Django 4.2.16 on 2026-07-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appsettings_free_ai_explanations_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='web_app_url',
            field=models.URLField(blank=True, help_text='Например https://xxxx.ngrok-free.app или https://xxx.trycloudflare.com — без /app/. Приоритетнее WEB_APP_URL из .env. После смены перезапусти telegram.py.', verbose_name='URL мини-приложения (домен)'),
        ),
    ]
