# Generated by Django 4.2.16 on 2026-08-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_web_app_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='max_daily_xp',
            field=models.PositiveIntegerField(default=1000, help_text='Максимальное количество XP, которое можно получить за 1 день для лидерборда.', verbose_name='Максимум XP в день (лимит турнира)'),
        ),
    ]
