# Generated by Django 4.2.16 on 2026-07-15 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Дата сессии')),
                ('status', models.CharField(choices=[('pending', 'Не начата'), ('in_progress', 'В процессе'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус')),
                ('tasks_total', models.PositiveSmallIntegerField(default=0, verbose_name='Всего заданий')),
                ('tasks_completed', models.PositiveSmallIntegerField(default=0, verbose_name='Выполнено')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP за сессию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sessions', to='students.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Ежедневная сессия',
                'verbose_name_plural': 'Ежедневные сессии',
                'ordering': ['-session_date'],
                'unique_together': {('student', 'session_date')},
            },
        ),
        migrations.CreateModel(
            name='SessionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('weak_topic', 'Слабая тема'), ('review', 'Повторение'), ('new', 'Новая тема')], default='new', max_length=20, verbose_name='Назначение')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Отвечено')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tasks', to='learning.dailysession', verbose_name='Сессия')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tasks', to='knowledge.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Задание сессии',
                'verbose_name_plural': 'Задания сессии',
                'ordering': ['order'],
                'unique_together': {('session', 'task')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Начало недели')),
                ('week_end', models.DateField(verbose_name='Конец недели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Недельная лига',
                'verbose_name_plural': 'Недельные лиги',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Ответ ученика')),
                ('is_correct', models.BooleanField(verbose_name='Правильно')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Время (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата попытки')),
                ('session_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='learning.sessiontask', verbose_name='Задание сессии')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='students.student', verbose_name='Ученик')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='knowledge.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Попытка ответа',
                'verbose_name_plural': 'Попытки ответов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIExplanationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_context', models.TextField(verbose_name='Контекст для ИИ')),
                ('ai_response', models.TextField(verbose_name='Ответ ИИ')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Модель ИИ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_explanations', to='learning.taskattempt', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'ИИ-разбор ошибки',
                'verbose_name_plural': 'ИИ-разборы ошибок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Правильных')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='Неправильных')),
                ('mastery_score', models.FloatField(default=0.0, verbose_name='Уровень освоения (0–1)')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to='students.student', verbose_name='Ученик')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='knowledge.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Освоение темы',
                'verbose_name_plural': 'Освоение тем',
                'unique_together': {('student', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='LeagueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_xp', models.PositiveIntegerField(default=0, verbose_name='XP за неделю')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Место')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='learning.weeklyleague', verbose_name='Лига')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_entries', to='students.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Участник лиги',
                'verbose_name_plural': 'Участники лиги',
                'ordering': ['rank', '-weekly_xp'],
                'unique_together': {('league', 'student')},
            },
        ),
    ]
