# Generated by Django 4.2.16 on 2026-07-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_examcollection_examvariant_varianttask'),
        ('students', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVariantProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Пройден')], default='not_started', max_length=20, verbose_name='Статус')),
                ('correct_count', models.PositiveSmallIntegerField(default=0, verbose_name='Верно')),
                ('wrong_count', models.PositiveSmallIntegerField(default=0, verbose_name='Ошибки')),
                ('score_percent', models.FloatField(default=0.0, verbose_name='% верных')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
            ],
            options={
                'verbose_name': 'Прогресс по варианту',
                'verbose_name_plural': 'Прогресс по вариантам',
                'ordering': ['variant__collection', 'variant__number'],
            },
        ),
        migrations.AlterModelOptions(
            name='dailysession',
            options={'ordering': ['-session_date', '-created_at'], 'verbose_name': 'Учебная сессия', 'verbose_name_plural': 'Учебные сессии'},
        ),
        migrations.AlterUniqueTogether(
            name='dailysession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailysession',
            name='exam_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='knowledge.examvariant', verbose_name='Вариант сборника'),
        ),
        migrations.AddField(
            model_name='dailysession',
            name='kind',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('train', 'Тренировка'), ('variant', 'Вариант из сборника'), ('mistakes', 'Ошибки')], db_index=True, default='daily', max_length=20, verbose_name='Тип сессии'),
        ),
        migrations.AddConstraint(
            model_name='dailysession',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'daily')), fields=('student', 'session_date'), name='uniq_daily_session_per_student_date'),
        ),
        migrations.AddField(
            model_name='studentvariantprogress',
            name='last_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_progress_links', to='learning.dailysession', verbose_name='Последняя сессия'),
        ),
        migrations.AddField(
            model_name='studentvariantprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_progress', to='students.student', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='studentvariantprogress',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='knowledge.examvariant', verbose_name='Вариант'),
        ),
        migrations.AlterUniqueTogether(
            name='studentvariantprogress',
            unique_together={('student', 'variant')},
        ),
    ]
