# Generated by Django 4.2.16 on 2026-07-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_studentvariantprogress_alter_dailysession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysession',
            name='max_primary',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Макс. первичный (за сессию)'),
        ),
        migrations.AddField(
            model_name='dailysession',
            name='primary_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Сумма первичных баллов за сессию (логика РИКЗ)', verbose_name='Первичный балл'),
        ),
        migrations.AddField(
            model_name='dailysession',
            name='test_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Перевод по шкале РИКЗ; для полной сессии ближе к ЦТ', null=True, verbose_name='Тестовый балл (оценка)'),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='max_points',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Макс. первичные за задание'),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='points_earned',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Первичные баллы'),
        ),
    ]
