# Generated by Django 4.2.16 on 2026-08-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_scoring_and_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время сдачи бланка'),
        ),
        migrations.AddField(
            model_name='dailysession',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=10800, help_text='180 минут для ЦТ/ЦЭ', verbose_name='Лимит времени (сек)'),
        ),
        migrations.AddField(
            model_name='dailysession',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Затраченное время (сек)'),
        ),
        migrations.AlterField(
            model_name='dailysession',
            name='kind',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('train', 'Тренировка'), ('variant', 'Вариант из сборника'), ('exam', 'Симулятор ЦТ/ЦЭ'), ('mistakes', 'Ошибки')], db_index=True, default='daily', max_length=20, verbose_name='Тип сессии'),
        ),
    ]
