# Generated by Django 4.2.16 on 2026-08-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_dailysession_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyleague',
            options={'ordering': ['-week_start'], 'verbose_name': 'Лига / Турнир', 'verbose_name_plural': 'Лиги и Турниры'},
        ),
        migrations.AddField(
            model_name='weeklyleague',
            name='period_type',
            field=models.CharField(choices=[('week', 'Недельная лига'), ('month', 'Месячный турнир')], default='week', max_length=20, verbose_name='Тип периода'),
        ),
        migrations.AddField(
            model_name='weeklyleague',
            name='prize_first_place',
            field=models.CharField(blank=True, default='🥇 1 место: Подписка Яндекс Плюс на 3 месяца', max_length=255, verbose_name='Приз за 1 место'),
        ),
        migrations.AddField(
            model_name='weeklyleague',
            name='prize_second_place',
            field=models.CharField(blank=True, default='🥈 2 место: Telegram Premium на 1 месяц', max_length=255, verbose_name='Приз за 2 место'),
        ),
        migrations.AddField(
            model_name='weeklyleague',
            name='prize_third_place',
            field=models.CharField(blank=True, default='🥉 3 место: Pro-подписка в приложении на 30 дней', max_length=255, verbose_name='Приз за 3 место'),
        ),
        migrations.AddField(
            model_name='weeklyleague',
            name='prizes_text',
            field=models.TextField(blank=True, verbose_name='Дополнительное описание призов'),
        ),
        migrations.AddField(
            model_name='weeklyleague',
            name='title',
            field=models.CharField(default='Недельный турнир', max_length=200, verbose_name='Название акции/турнира'),
        ),
        migrations.AlterField(
            model_name='weeklyleague',
            name='week_end',
            field=models.DateField(verbose_name='Конец периода'),
        ),
        migrations.AlterField(
            model_name='weeklyleague',
            name='week_start',
            field=models.DateField(verbose_name='Начало периода'),
        ),
    ]
