# Generated by Django 4.2.16 on 2026-08-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_weeklyleague_options_weeklyleague_period_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagueentry',
            options={'ordering': ['rank', '-test_score', '-primary_score', '-weekly_xp'], 'verbose_name': 'Участник лиги', 'verbose_name_plural': 'Участники лиги'},
        ),
        migrations.AddField(
            model_name='leagueentry',
            name='primary_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Первичный балл'),
        ),
        migrations.AddField(
            model_name='leagueentry',
            name='test_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Тестовый балл'),
        ),
        migrations.AlterField(
            model_name='leagueentry',
            name='weekly_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='XP за период'),
        ),
        migrations.AlterField(
            model_name='weeklyleague',
            name='prize_first_place',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Приз за 1 место'),
        ),
        migrations.AlterField(
            model_name='weeklyleague',
            name='prize_second_place',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Приз за 2 место'),
        ),
        migrations.AlterField(
            model_name='weeklyleague',
            name='prize_third_place',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Приз за 3 место'),
        ),
        migrations.AlterField(
            model_name='weeklyleague',
            name='title',
            field=models.CharField(default='Турнир', max_length=200, verbose_name='Название акции/турнира'),
        ),
    ]
