# Generated by Django 4.2.16 on 2026-08-22 15:48

from django.db import migrations, models


def merge_duplicate_leagues(apps, schema_editor):
    WeeklyLeague = apps.get_model('learning', 'WeeklyLeague')
    LeagueEntry = apps.get_model('learning', 'LeagueEntry')
    duplicates = (
        WeeklyLeague.objects.values('period_type', 'week_start')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
    )
    for group in duplicates.iterator():
        leagues = list(
            WeeklyLeague.objects.filter(
                period_type=group['period_type'],
                week_start=group['week_start'],
            ).order_by('id')
        )
        keeper = leagues[0]
        for duplicate in leagues[1:]:
            for entry in LeagueEntry.objects.filter(league=duplicate).iterator():
                current = LeagueEntry.objects.filter(
                    league=keeper,
                    student_id=entry.student_id,
                ).first()
                if current:
                    current.weekly_xp += entry.weekly_xp
                    current.primary_score += entry.primary_score
                    current.test_score = max(current.test_score, entry.test_score)
                    ranks = [rank for rank in (current.rank, entry.rank) if rank is not None]
                    current.rank = min(ranks) if ranks else None
                    current.save(update_fields=['weekly_xp', 'primary_score', 'test_score', 'rank'])
                    entry.delete()
                else:
                    entry.league = keeper
                    entry.save(update_fields=['league'])
            duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_leagueentry_options_leagueentry_primary_score_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailysession',
            index=models.Index(fields=['student', 'status', 'kind', '-id'], name='learning_da_student_e3894a_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysession',
            index=models.Index(fields=['student', '-session_date'], name='learning_da_student_c3cf5a_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontask',
            index=models.Index(fields=['session', 'is_answered', 'order'], name='learning_se_session_b93016_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['student', '-created_at'], name='learning_ta_student_787f64_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['student', 'task', 'is_correct'], name='learning_ta_student_9fb734_idx'),
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['student', 'mastery_score'], name='learning_to_student_7b7aec_idx'),
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['student', 'wrong_count'], name='learning_to_student_210d69_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyleague',
            index=models.Index(fields=['period_type', 'is_active', '-week_start'], name='learning_we_period__b2be56_idx'),
        ),
        migrations.RunPython(merge_duplicate_leagues, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='weeklyleague',
            constraint=models.UniqueConstraint(fields=('period_type', 'week_start'), name='uniq_league_period_start'),
        ),
    ]
