# Generated by Django 4.2.16 on 2026-09-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_dailysession_learning_da_student_e3894a_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['student', 'session_task', '-created_at'], name='learning_ta_student_6947d4_idx'),
        ),
    ]
