# Generated by Django 4.2.16 on 2026-09-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_topicextratask'),
        ('learning', '0008_taskattempt_learning_ta_student_6947d4_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattempt',
            name='extra_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='knowledge.topicextratask', verbose_name='Дополнительное задание'),
        ),
        migrations.AlterField(
            model_name='taskattempt',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='knowledge.task', verbose_name='Задание'),
        ),
    ]
